In [2]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [3]:
a= 0.1+0.2==0.3
print(a)

False


In [7]:
sub=0.1*0.2
print(sub)

0.020000000000000004


In [13]:
import numpy as np
a = np.array((10,20,30,40))
print(a)

[10 20 30 40]


In [15]:
import numpy as np
arr = np.array([1,2,3,4,5],dtype=float)
print(arr)

[1. 2. 3. 4. 5.]


In [6]:
import numpy as np
a = np.eye(10)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [16]:
import numpy as np
a = np.empty((4,4))
print(a)

[[ 1.63794309e-307 -2.25921049e+021  1.79945544e-311  0.00000000e+000]
 [ 0.00000000e+000  9.97305201e-317  5.28598492e-308  2.05833592e-312]
 [ 1.32329363e-292  0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  1.03977794e-312  1.63779370e-307  2.12199579e-314]]


In [24]:
import numpy as np
a = np.arange(1,20,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [26]:
import numpy as np
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
import numpy as np
a = np.array([1,2|3,4])
print(a.flatten())

[1 3 4]


In [37]:
a = np.array([10,20,30,40])
print(a[0])

10


In [42]:
import numpy as np
a = np.array([[1,2,3],
              [39,87,6],
              [56,20,3]])
print(a[0,0])
print(a[2,2])

1
3


In [43]:
import numpy as np
a = np.array([55,98,32])
b = np.array([2,5,9])
print(a+b)

[ 57 103  41]


In [44]:
import numpy as np
a = np.array([55,98,32])
b = np.array([2,5,9])
print(a-b)

[53 93 23]


In [45]:
import numpy as np
a = np.array([55,98,32])
b = np.array([2,5,9])
print(a*b)

[110 490 288]


In [46]:
import numpy as np
a = np.array([55,98,32])
b = np.array([2,5,9])
print(a/b)

[27.5        19.6         3.55555556]


In [47]:
import numpy as np
a = np.array([55,98,32])
b = np.array([2,5,9])
print(a**b)

[     3025 449273376         0]


In [1]:
import numpy as np
marks = np.array([55,98,40,59,32])
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.sum(marks))
print(np.median(marks))
print(np.std(marks))


56.8
98
32
284
55.0
22.815784010197852


In [2]:
import numpy as np
a = np.array([1,2,3])
print(a+10)

[11 12 13]


In [3]:
import numpy as np
marks = np.array([55,98,40,59,32])
print("Average",(np.mean(marks)))
print("Maximum",(np.max(marks)))
print("Minumum",(np.min(marks)))

Average 56.8
Maximum 98
Minumum 32


In [8]:
import numpy as np
dt = np.dtype([('name', 'U20'), ('old_salary', 'f8'), ('increment', 'f8')])
data = np.array([
    ("Alice", 50000, 5000),
    ("Bob", 60000, 5500),
    ("Charlie", 45000, 4000),
    ("David", 70000, 7000),
    ("Eva", 55000, 4800),
    ("Frank", 65000, 6000),
    ("Grace", 48000, 4200),
    ("Hannah", 80000, 8500),
    ("Ian", 52000, 5000),
    ("Jack", 59000, 5300)
], dtype=dt)

differences = new_salaries - data['old_salary']
avg_old = np.mean(data['old_salary'])
avg_new = np.mean(new_salaries)
avg_diff = np.mean(differences)
print("Name       | Old Salary | New Salary | Difference")
print("-" * 50)
for i in range(len(data)):
    print(f"{data['name'][i]:<10} | {data['old_salary'][i]:<10.2f} | {new_salaries[i]:<10.2f} | {differences[i]:<10.2f}")

print("-" * 50)
print(f"Averages   | {avg_old:<10.2f} | {avg_new:<10.2f} | {avg_diff:<10.2f}")

<class 'numpy._core._exceptions._UFuncNoLoopError'>: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U10'), dtype('float64')) -> None

In [9]:
import numpy as np
age = 25
salary = 54000.50
name = "Alice"
is_developer = True
print(type(salary)) 

<class 'float'>


In [10]:
fruits = ["apple", "banana", "cherry"]
fruits.append("date")
print(fruits[0])
coordinates = (10.0, 20.0)
employee = {
    "name": "Bob",
    "age": 30,
    "role": "Data Analyst"
}
print(employee["name"])

apple
Bob


In [11]:
import numpy as np
for fruit in fruits:
    print(fruit)
for i in range(1, 5):
    print(i)  # Prints 1, 2, 3, 4
count = 0
while count < 3:
    print(count)
    count += 1

apple
banana
cherry
date
1
2
3
4
0
1
2


In [14]:
import panda as pd
print(pd._version_)

<class 'ModuleNotFoundError'>: No module named 'panda'

In [15]:
import panda as pd
marks = pd.Series([80,90,75,60])
print(marks)

<class 'ModuleNotFoundError'>: No module named 'panda'